---
- name: Find the testfile.txt file
  hosts: all
 #become_method: runas

  tasks:
  - name: Download file from S3 bucket with authentication
    win_get_url:
      url: https://s3-us-west-2.amazonaws.com/ansible-demo-test-bucket-101/testFile.txt
      dest: 'c:\Users\Administrator\Desktop\testfile.txt'
  
  - name: Use stat to retrieve facts for the file that was transferred
    win_stat:
      path: 'c:\Users\Administrator\Desktop\testfile.txt'
    register: p
      
  - name: Assert that transferred file exists
    assert:
      that:
        - p.stat.exists
