---
- name: Find the demo.txt file
  hosts: all
 #become_method: runas

  tasks:
  - name: Download file from FTP with authentication
    win_get_url:
      url: https://s3-us-west-2.amazonaws.com/ansible-demo-test-bucket-101/testFile.txt
      dest: 'c:\Users\Administrator\Desktop\mattdemo.txt'

